### ISSUE TITLE
feat: Unify component and service names

### ISSUE THREAD

**Issue by valentingavran** [valentingavran/anglify#147]
### Feature Description

We should avoid and rename service names like SnackbarService. There is also the question of whether we should prefix Anglify in front of each service and component name:

- AnglifyStep
- AnglifyStepper
- AnglifyDialog
- ...

### Use Case

- Consistency improves the developer experience.
- The Anglify prefix lets the developer know at a glance that the service is provided by Anglify. Angular Material does the same thing (`MatSnackbar`, ...)
- For the developer it doesn't matter if this is a service or a directive (Stepper Step=Directive, Snackbar = Service). He only wants to be able to interact with it

**Comment by iCrawl** [comment]
Especially for the last point:

I don't think the developer doesn't "care" what it is, and just wants to "interact" with it.
When I import something inside the component code, whether that be when I do

```ts
public constructor(private readonly someService: SomeService) {}
```
It is very easy if the suffix is there, because I know I want the service to be here.

If I want to do ViewChild or ContentChild matching via the directive, I like to do:
 ```ts
@ViewChild(SomeDirective)
public readonly someElement!: SomeDirective;
 ```

I would argue it makes things a lot easier knowing "I need to import the directive here" or "I want to import the service here" and import autocompletion makes this a lot easier too.
