### ISSUE TITLE
feat: Directive equal input property names

### ISSUE THREAD

**Issue by Satellite37** [valentingavran/anglify#149]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Reproduction

Steps to reproduce:

If you apply the tooltip directive to any Component you provide a position throught the position Input property like this :

`<button anglifyButton anglifyTooltip="Tooltip" position="top">Top</button>`

This is missleading if you want to comibe multiple directives which provides the position Input property position like the badge directive:

`<button anglifyButton appearance="contained" anglifyTooltip="Tooltip" position="top" anglifyBadge="Any content" badgePosition="top">Contained</button>`

### Expected Behavior

The input property position should be renamed to something like tooltipPosition:

<button anglifyButton anglifyTooltip="Tooltip" tooltipPosition="top">Top</button>

### Actual Behavior

`<button anglifyButton anglifyTooltip="Tooltip" position="top">Top</button>`

### Environment

- Angular:
- Anglify:

**Comment by valentingavran** [comment]
@iCrawl This is a bug, because directives that have the same input properties overwrite each other if they are both mounted on the same element.

If I only want to change the position of the badge on a button, that has a badge and a tooltip, then the position of the tooltip also changes, which is not the intention.

**Comment by iCrawl** [comment]
That one is hard.

I think the config one might be better because this way we can also have the config object in the component code itself and then just assign it a variable and pass it like
```html
<button anglifyButton anglifyTooltip="Tooltip" [anglifyTooltipConfig]="tooltipConfig">My Button</button>
```

But if we go a bit further with this, do we do the same thing with buttons?
Because right now we have button props as `appearance="outlined"` and stuff too.

**Comment by valentingavran** [comment]
@iCrawl The only exception would be the button directive. For this directive I would not use a configuration object.
